repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 3f92c8d
    hooks:
    -   id: autopep8
- repo: https://gitlab.com/pycqa/flake8
  rev: '5.0.4'
  hooks:
  -   id: flake8
      args: ['--max-line-length', '120', '--ignore', 'F405, F403']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: fde4bb9
  hooks:
    - id: mypy
