[tool.poetry]
name = "spaceship"
version = "0.1.0"
description = ""
authors = ["Roman <academboyhtml@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
